In [7]:
import pandas as pd

df_claim = pd.read_csv('final-dataset(A1-31306samples)-train-topicmodel.csv')
df_claim.head()

,publication_number,country_code,kind_code,title,abstract,claims,publication_date,ipc_code,cpc_code,first_claim,claim_lengths,sub_classes,sub_class,abstract_lengths
0,US2020097067A1,US,A1,Artificial Intelligence System and Interactive...,"A reality interactive responding system, compr...","1 . A reality interactive responding system, c...",20200326,G06F9/448,G16H40/67,"1 . A reality interactive responding system, c...",200,"['G06F9/448', 'G16H40/67']","['G06F', 'G16H']",123
1,US2020098473A1,US,A1,Data Storage and Retrieval System for Non-Cont...,A web-based interface enables medical personne...,What is claimed is: \n \n 1 . A da...,20200326,G16H40/67,H04L67/1097,What is claimed is: 1 . A data storage and ret...,200,"['G16H40/67', 'H04L67/1097']","['G16H', 'H04L']",142
2,US2020098451A1,US,A1,Hybrid analysis framework for prediction of ou...,A facility for predicting patient outcomes on ...,"1 . A method in a computing system, comprising...",20200326,G16H10/20,G16H10/20,"1 . A method in a computing system, comprising...",200,"['G16H10/20', 'G16H10/20']","['G16H', 'G16H']",81
3,US2020098458A1,US,A1,Medical cannabis platform with physician and p...,"Through a physician&#39;s portal, a platform c...",What is claimed is: \n \n 1 . A me...,20200326,G16H80/00,A61K36/185,What is claimed is: 1 . A method for providing...,200,"['G16H80/00', 'A61K36/185']","['G16H', 'A61K']",148
4,US2020093988A1,US,A1,Patient day planning systems and methods,"Infusion systems, infusion devices, and relate...",What is claimed is: \n \n 1 . A me...,20200326,G16H20/17,A61M2230/201,What is claimed is: 1 . A method of monitoring...,200,"['G16H20/17', 'A61M2230/201']","['G16H', 'A61M']",110

In [8]:
len(df_claim)

31306

In [9]:
first_record = df_claim['first_claim'][1]
first_record

'What is claimed is: 1 . A data storage and retrieval system for non-contiguous medical device data, the system comprising: a medical device, connectable to a computer network, subject to occasional gaps in connectivity to the computer network, and configured to automatically repeatedly capture status information about the medical device and send messages containing the status information via the computer network; a network connectivity log configured to automatically record: (a) times at which the medical device connects to the computer network and (b) times at which the medical device disconnects from the computer network; a data store configured to automatically: store digital media data in a media file; and provide a requested portion, less than all, of the stored media file in response to a provision request, wherein the provision request includes an index, relative to an end of the media file, that corresponds to the requested portion; a media server, connectable to the computer network and configured to automatically: receive the messages via the computer network; store status information from received messages into the data store, wherein status information from consecutive received messages is stored contiguously in the data store, notwithstanding the occasional gaps in connectivity between the medical'

In [10]:
x = len(df_claim['first_claim'][1])
print(x)

1331

In [11]:
import torch
from bertopic import BERTopic
from hdbscan import HDBSCAN
from umap import UMAP
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer

# Check if GPU is available and set the device accordingly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the Sentence Transformers model
sentence_model = SentenceTransformer('AI-Growth-Lab/PatentSBERTa')
#sentence_model = SentenceTransformer("all-MiniLM-L6-v2", device=device)

# Adjust UMAP hyperparameters
umap_model = UMAP(n_neighbors=3, 
                  n_components=3, 
                  min_dist=0.05, 
                  metric='cosine', 
                  random_state=100,
                  n_jobs=-1)  # Utilize all available CPU cores for UMAP preprocessing

# Adjust HDBSCAN hyperparameters
hdbscan_model = HDBSCAN( min_cluster_size=80,
                        min_samples=40, 
                        metric='euclidean', 
                        cluster_selection_method='eom', 
                        prediction_data=True)

# Adjust CountVectorizer hyperparameters
vectorizer_model = CountVectorizer(ngram_range=(1, 3), min_df=10, max_df=0.5)


# c-TF-IDF
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

# Run Model
topic_model = BERTopic(umap_model=umap_model,
                       embedding_model=sentence_model, 
                       hdbscan_model=hdbscan_model, 
                       vectorizer_model=vectorizer_model,
                       ctfidf_model=ctfidf_model,
                       verbose=True)

# Replace 'df['first_claim']' with your data source for the first_claim column
topics, probabilities = topic_model.fit_transform(df_claim['first_claim'])

Batches:   0%|          | 0/979 [00:00<?, ?it/s]

2023-09-24 11:30:47,513 - BERTopic - Transformed documents to Embeddings
2023-09-24 11:31:34,730 - BERTopic - Reduced dimensionality
2023-09-24 11:31:37,339 - BERTopic - Clustered reduced embeddings

In [12]:
import gensim.corpora as corpora
from gensim.models.coherencemodel import CoherenceModel

documents = pd.DataFrame({"Document": df_claim['first_claim'],
                          "ID": range(len(df_claim['first_claim'])),
                          "Topic": topics})

documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
cleaned_docs = topic_model._preprocess_text(documents_per_topic.Document.values)

# Extract vectorizer and analyzer from BERTopic
vectorizer = topic_model.vectorizer_model
analyzer = vectorizer.build_analyzer()

# Extract features for Topic Coherence evaluation
words = vectorizer.get_feature_names_out()
tokens = [analyzer(doc) for doc in cleaned_docs]
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]
topic_words = [[words for words, _ in topic_model.get_topic(topic)] for topic in range(len(set(topics))-1)]


# Evaluate
coherence_model = CoherenceModel(topics=topic_words, 
                                 texts=tokens, 
                                 corpus=corpus,
                                 dictionary=dictionary, 
                                 coherence='c_npmi')
coherence_c_nmpi = coherence_model.get_coherence()
print("c_npmi is: ",coherence_c_nmpi)

c_npmi is:  -0.15626478182216264

In [13]:
import gensim.corpora as corpora
from gensim.models.coherencemodel import CoherenceModel

documents = pd.DataFrame({"Document":df_claim['first_claim'],
                          "ID": range(len(df_claim['first_claim'])),
                          "Topic": topics})
documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
cleaned_docs = topic_model._preprocess_text(documents_per_topic.Document.values)

# Extract vectorizer and analyzer from BERTopic
vectorizer = topic_model.vectorizer_model
analyzer = vectorizer.build_analyzer()

# Extract features for Topic Coherence evaluation
words = vectorizer.get_feature_names_out()
tokens = [analyzer(doc) for doc in cleaned_docs]
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]
topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
               for topic in range(len(set(topics))-1)]

# Evaluate
coherence_model = CoherenceModel(topics=topic_words, 
                                 texts=tokens, 
                                 corpus=corpus,
                                 dictionary=dictionary, 
                                 coherence='c_v')
coherence_CV= coherence_model.get_coherence()
print("C_V is: ", coherence_CV)

C_V is:  0.32861081695473926

In [14]:
import gensim.corpora as corpora
from gensim.models.coherencemodel import CoherenceModel

documents = pd.DataFrame({"Document":df_claim['first_claim'],
                          "ID": range(len(df_claim['first_claim'])),
                          "Topic": topics})
documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
cleaned_docs = topic_model._preprocess_text(documents_per_topic.Document.values)

# Extract vectorizer and analyzer from BERTopic
vectorizer = topic_model.vectorizer_model
analyzer = vectorizer.build_analyzer()

# Extract features for Topic Coherence evaluation
words = vectorizer.get_feature_names_out()
tokens = [analyzer(doc) for doc in cleaned_docs]
dictionary = corpora.Dictionary(tokens)
corpus = [dictionary.doc2bow(token) for token in tokens]
topic_words = [[words for words, _ in topic_model.get_topic(topic)] 
               for topic in range(len(set(topics))-1)]

# Evaluate
coherence_model = CoherenceModel(topics=topic_words, 
                                 texts=tokens, 
                                 corpus=corpus,
                                 dictionary=dictionary, 
                                 coherence='u_mass')
coherence_u_mass= coherence_model.get_coherence()
print("u_mass is: ", coherence_u_mass)

u_mass is:  -0.5913988250513408

In [15]:
 topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,12235,-1_sleep_clinical trial_ecg_the surgical,"[sleep, clinical trial, ecg, the surgical, med...",[1 ) SYSTEM FOR THE PREVENTION AND PREDICTION ...
1,0,5409,0_claimed is system_is system_is system for_cl...,"[claimed is system, is system, is system for, ...","[What is claimed is: 1 . A system for a user, ..."
2,1,1388,1_health care provider_of claim method_medical...,"[health care provider, of claim method, medica...",[1 . A computer-implemented method for providi...
3,2,1208,2_claimed is computer_is method comprising_the...,"[claimed is computer, is method comprising, th...",[What is claimed is: 1 . A computerized method...
4,3,794,3_medical images_the medical image_image the m...,"[medical images, the medical image, image the ...",[What is claimed is: 1 . A method for converti...
5,4,751,4_medical images_medical imaging_exam_in claim...,"[medical images, medical imaging, exam, in cla...",[1 . A method of administering medical digital...
6,5,693,5_personal health_care system_data the system_...,"[personal health, care system, data the system...",[1 . An information management system comprisi...
7,6,467,6_claim 21_20 canceled_canceled 21_20 canceled 21,"[claim 21, 20 canceled, canceled 21, 20 cancel...",[1 - 11 . (canceled) 12 - 18 . (canceled) 19 ....
8,7,465,7_gene_dna_genes_nucleic,"[gene, dna, genes, nucleic, genomic, sequencin...",[What is claimed is: 1 . A method for determin...
9,8,404,8_insulin_blood glucose_glucose level_bolus,"[insulin, blood glucose, glucose level, bolus,...",[1 . A method of regulating blood glucose usin...
10,9,391,9_the apparatus of_apparatus as_an apparatus c...,"[the apparatus of, apparatus as, an apparatus ...","[1 . A personal monitoring apparatus, comprisi..."
11,10,387,10_digital health_wait_patient health_appointment,"[digital health, wait, patient health, appoint...",[What is claimed is: 1 . A computerized method...
12,11,353,11_the pharmacy_dispensing_prescriber_prescrip...,"[the pharmacy, dispensing, prescriber, prescri...",[1 . A method for verifying a multiple prescri...
13,12,322,12_and health care_health care data_words_heal...,"[and health care, health care data, words, hea...","[1 . A method of generating, storing, relating..."
14,13,291,13_medical imaging_image processing_medical im...,"[medical imaging, image processing, medical im...","[1 . A system, comprising: at least one storag..."
15,14,286,14_the medical image_processing apparatus_appa...,"[the medical image, processing apparatus, appa...","[1 . A diagnostic supporting apparatus, compri..."
16,15,270,15_bone_mr_the bone_segmentation,"[bone, mr, the bone, segmentation, mri, spine,...","[1 . A method, comprising: acquiring a plurali..."
17,16,262,16_medical device of_portable device_the porta...,"[medical device of, portable device, the porta...",[1 . A portable electronic device for use in a...
18,17,255,17_of genetic_nucleotide_acid_biological sample,"[of genetic, nucleotide, acid, biological samp...",[1 . A computer-implemented method comprising:...
19,18,234,18_prescription drug_discount_of the prescript...,"[prescription drug, discount, of the prescript...",[What is claimed is: 1 . A computer-implemente...
20,19,220,19_17_claim 16_16 wherein_claim 16 wherein,"[17, claim 16, 16 wherein, claim 16 wherein, 1...",[1 - 16 . (canceled) 17 . A method for imaging...
21,20,220,20_insulin_blood glucose_basal_analyte,"[insulin, blood glucose, basal, analyte, gluco...","[1 . A device for treatment of a subject, wher..."
22,21,219,21_dental_tooth_teeth_the dental,"[dental, tooth, teeth, the dental, appliance, ...",[What is claimed is: 1 . A dental appliance sy...
23,22,194,22_medium of claim_medium of_readable medium o...,"[medium of claim, medium of, readable medium o...",[1 . A non-transitory computer readable medium...
24,23,192,23_we claim method_benefit_coach_shapes,"[we claim method, benefit, coach, shapes, figu...",[I claim: 1 . A method for receiving an approv...
25,24,184,24_terminals_medical facility_physicians_servers,"[terminals, medical facility, physicians, serv...",[1 . A system for delivering health-care conti...
26,25,183,25_physiological signal_method of monitoring_m...,"[physiological signal, method of monitoring, m...",[1 . A method of determining a value of a phys...
27,26,183,26_the non transitory_the infusion_is non_infu...,"[the non transitory, the infusion, is non, inf...",[What is claimed is: 1 . A non-transitory comp...
28,27,180,27_the ultrasound_an ultrasound_ultrasound ima...,"[the ultrasound, an ultrasound, ultrasound ima...",[1 . An ultrasound system comprising: an ultra...
29,28,157,28_fitness_athletic_physical activity_an exercise,"[fitness, athletic, physical activity, an exer...",[1 . A method for determining at least one phy...
30,29,152,29_the invention_invention_renal_as follows,"[the invention, invention, renal, as follows, ...",[The invention claimed is: 1 . One or more com...
31,30,150,30_the exercise_fitness_an exercise_the fitness,"[the exercise, fitness, an exercise, the fitne...",[What is claimed is: 1 . A computer-system-imp...
32,31,149,31_eeg_electrical stimulation_electrode_the el...,"[eeg, electrical stimulation, electrode, the e...",[What is claimed is: 1 . An electronic device ...
33,32,147,32_said particular_particular patient_said par...,"[said particular, particular patient, said par...",[1 . A consent information management system s...
34,33,146,33_mental state_from the wearable_wearable sen...,"[mental state, from the wearable, wearable sen...",[1 . A computer-system-implemented method of p...
35,34,136,34_coronary_artery_blood flow_blood vessel,"[coronary, artery, blood flow, blood vessel, v...",[What is claimed is: 1 . A method for calculat...
36,35,134,35_media of_the media_computer storage_is one or,"[media of, the media, computer storage, is one...",[What is claimed is: 1 . One or more computer ...
37,36,134,36_risk score_infection_geographic_infected,"[risk score, infection, geographic, infected, ...",[What is claimed is: 1 . A method for determin...
38,37,129,37_beat_arrhythmia_ecg_the heart,"[beat, arrhythmia, ecg, the heart, the cardiac...",[What is claimed is: 1 . A method comprising: ...
39,38,118,38_infusion pump_the infusion pump_the infusio...,"[infusion pump, the infusion pump, the infusio...",[1 . A wearable infusion pump assembly compris...
40,39,116,39_nurse_identification device_patient monitor...,"[nurse, identification device, patient monitor...","[1 . A patient monitoring system, comprising: ..."
41,40,104,40_the information processing_an information p...,"[the information processing, an information pr...",[1 . An information processing system comprisi...
42,41,96,41_nutritional_dietary_recipe_meal,"[nutritional, dietary, recipe, meal, diet, the...","[1 . A method for supporting dietary habits, c..."
43,42,96,42_29_28_condition data_subjective,"[29, 28, condition data, subjective, patient h...",[1 - 28 . (canceled) 29 . A method for managin...
44,43,95,43_transplant_we claim method_survival_qualifying,"[transplant, we claim method, survival, qualif...",[We claim: 1 . A method of providing a reward ...
45,44,90,44_claim as_invention_in claim comprising_said...,"[claim as, invention, in claim comprising, sai...",[What is claimed is: 1 . A method for AI proce...
46,45,89,45_of food_food items_nutritional_the food,"[of food, food items, nutritional, the food, d...",[What is claimed is: 1 . A method comprising: ...
47,46,88,46_the radiation_radiographic_the radiographic...,"[the radiation, radiographic, the radiographic...",[What is claimed is: 1 . An image processing d...
48,47,87,47_physiological condition_the physiological c...,"[physiological condition, the physiological co...",[What is claimed is: 1 . A method of estimatin...
49,48,86,48_rehabilitation_the stream_nlp_to the sensed,"[rehabilitation, the stream, nlp, to the sense...",[What is claimed is: 1 . A computer program pr...
50,49,84,49_media of_the media_storage media_computer s...,"[media of, the media, storage media, computer ...",[1 . One or more computer storage media having...
51,50,83,50_dispensing_compartment_the dispensing_dispe...,"[dispensing, compartment, the dispensing, disp...","[We claim: 1 . A dispensing station, comprisin..."

In [16]:
#adding topics and probs for eachdoc in dataset
df_claim['topics'] = topics
df_claim['prob'] = probabilities
df_claim_topic=df_claim[["publication_number","title","first_claim","sub_classes","sub_class","topics","prob"]]
df_claim_topic

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob
0,US2020097067A1,Artificial Intelligence System and Interactive...,"1 . A reality interactive responding system, c...","['G06F9/448', 'G16H40/67']","['G06F', 'G16H']",-1,0.000000
1,US2020098473A1,Data Storage and Retrieval System for Non-Cont...,What is claimed is: 1 . A data storage and ret...,"['G16H40/67', 'H04L67/1097']","['G16H', 'H04L']",0,1.000000
2,US2020098451A1,Hybrid analysis framework for prediction of ou...,"1 . A method in a computing system, comprising...","['G16H10/20', 'G16H10/20']","['G16H', 'G16H']",-1,0.000000
3,US2020098458A1,Medical cannabis platform with physician and p...,What is claimed is: 1 . A method for providing...,"['G16H80/00', 'A61K36/185']","['G16H', 'A61K']",-1,0.000000
4,US2020093988A1,Patient day planning systems and methods,What is claimed is: 1 . A method of monitoring...,"['G16H20/17', 'A61M2230/201']","['G16H', 'A61M']",47,1.000000
...,...,...,...,...,...,...,...
31301,US2016253489A1,User authentication system,1 . A user authentication system comprising: a...,"['G16H10/60', 'G06F21/32']","['G16H', 'G06F']",5,0.900515
31302,US2016253467A1,"Diagnosis support apparatus and method, and no...",What is claimed is: 1 . A diagnosis support ap...,"['G16H10/60', 'A61B5/743']","['G16H', 'A61B']",0,1.000000
31303,US2016253462A1,Novel open-access scheduling system that optim...,1 . A medical appointment scheduling system co...,"['G16H40/20', 'G06F19/327']","['G16H', 'G06F']",-1,0.000000
31304,US2016249985A1,Interrelated point acquisition for navigated s...,"1 . A data processing, comprising a computer h...","['G16H20/40', 'G06F19/324']","['G16H', 'G06F']",4,0.996585
31305,US2016253465A1,Next generation lifestream application,1 . A method comprising: a healthcare server o...,"['G16H40/67', 'G16H50/20']","['G16H', 'G16H']",-1,0.000000

# prediction

In [17]:
import pandas as pd

df_claim_test = pd.read_csv('test-queries-USPTO(A1)-2023-G16H.csv')
df_claim_test.head()

,publication_numbers,abstract,first_claim,class_codes
0,US20230238130A1,A physiological sensor has light emitting sour...,1. A physiological monitoring device comprisin...,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/..."
1,US20230270344A1,A wearable monitoring device includes a band c...,"1. A monitoring device, comprising:\na band co...","A61B5/02405,A61B5/01,A61B5/16,A61B5/02055,A61B..."
2,US20230200909A1,A number of improvements are provided relating...,1-25. (canceled) 26. A method for guiding a fr...,"A61B17/17,A61B2090/061,A61B90/06,A61B2090/365,..."
3,US20230218347A1,Embodiments include a system for determining c...,1-184. (canceled) 185. A computer-implemented ...,"G06V10/46,G06V20/698,G06T2207/20112,G06T7/13,A..."
4,US20230063013A1,A community based response system for providin...,1. (canceled) 2. A community based response sy...,"H04M1/72418,G08B,G08,G08B25/016,G,H04W4/023,G1..."

# test1

In [18]:
df_claim_test.iloc[0]

publication_numbers                                      US20230238130A1
abstract               A physiological sensor has light emitting sour...
first_claim            1. A physiological monitoring device comprisin...
class_codes            A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...
Name: 0, dtype: object

In [19]:
test1 = df_claim_test.loc[0, 'first_claim']
test1

'1. A physiological monitoring device comprising:\nat least two LEDs, the at least two LEDs configured to emit light of at least two different wavelengths; at least one detector configured to detect at least a portion of the light emitted from the at least two LEDs after at least a portion of the light has been attenuated by tissue, the at least one detector configured to output at least one signal responsive to the detected light; a light block surrounding the at least one detector, the light block forming a cavity, the light block comprising a light-absorbing material, the light block including only one circular opening through which light is configured to pass, an area of the circular opening being smaller than a surface area of a facing surface of the at least one detector; and a processor configured to receive and process one or more signals responsive to the outputted at least one signal and determine a physiological parameter of a user responsive to the one or more signals. at least two LEDs, the at least two LEDs configured to emit light of at least two different wavelengths; at least one detector configured to detect at least a portion of the light emitted from the at least two LEDs after at least a portion of the light has been attenuated by tissue, the at least one detector configured to output at least one signal responsive to the detected light; a light block surrounding the at least one detector, the light block forming a cavity, the light block comprising a light-absorbing material, the light block including only one circular opening through which light is configured to pass, an area of the circular opening being smaller than a surface area of a facing surface of the at least one detector; and a processor configured to receive and process one or more signals responsive to the outputted at least one signal and determine a physiological parameter of a user responsive to the one or more signals.'

In [20]:
import numpy as np 

# Find topics
num_of_topics = 5
similar_topics, similarity = topic_model.find_topics(test1, top_n=num_of_topics); 

# Print results
print(f'The top {num_of_topics} similar topics are {similar_topics}, and the similarities are {np.round(similarity,2)}')

for idx, topic_idx in enumerate(similar_topics):
    topic = topic_model.get_topic(topic_idx)
    keywords = ' '.join(str(keyword) for keyword in topic[0])
    print(f"Topic {idx+1}: {keywords}")

The top 5 similar topics are [16, 25, 9, -1, 39], and the similarities are [0.79 0.79 0.79 0.78 0.77]
Topic 1: medical device of 0.27979274135764304
Topic 2: physiological signal 0.2792462222724727
Topic 3: the apparatus of 0.454426918737517
Topic 4: sleep 0.1240670651751376
Topic 5: nurse 0.33454800955968295

In [21]:
filter_topics_filter = df_claim_topic[df_claim_topic['topics'] == 16]
filter_topics_filter = filter_topics_filter.sort_values('prob', ascending=False)
filter_topics_filter

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob
16081,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.000000
10046,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.000000
13619,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.000000
13552,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.000000
13542,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.000000
...,...,...,...,...,...,...,...
12874,US2021307622A1,Doctor health monitoring system based on medic...,1 : A doctor health monitoring system based on...,"['A61B5/024', 'G16H50/20']","['A61B', 'G16H']",16,0.704687
10466,US2017325700A1,Real-time vagal monitoring and intervention,1 . (canceled) 2 . The monitoring device of cl...,"['G16H40/63', 'A61B5/02405']","['G16H', 'A61B']",16,0.703344
25894,US2011106553A1,Health management guideline advising device,1 . A health management guideline advising dev...,"['G16H20/30', 'G09B19/0092']","['G16H', 'G09B']",16,0.702570
25850,US2011093210A1,Measurement device and method of controlling t...,1 . A measurement device comprising: a first m...,"['G16H40/67', 'G16H40/67']","['G16H', 'G16H']",16,0.701239
30098,US2015335244A1,Monitor Defibrillator Telemedicine Server,1 . A monitor defibrillator having an integrat...,"['G16H20/30', 'H04L63/0245']","['G16H', 'H04L']",16,0.694678

In [22]:
# Define the range of topic IDs you want to retrieve documents for
selected_topic_range =[16, 25, 9, -1, 39]  # Replace with your desired range of topic IDs

# Create an empty DataFrame to store the top 10 documents
top_10_documents_test1 = pd.DataFrame()

# Iterate through the selected topic IDs
for selected_topic_id in selected_topic_range:
    # Filter the dataset based on the current topic ID
    filtered_df = df_claim_topic[df_claim_topic['topics'] == selected_topic_id]
    
    # Sort the filtered dataset by similarity scores in descending order
    sorted_df = filtered_df.sort_values(by='prob', ascending=False)
    
    # Retrieve the top 10 documents for the current topic
    top_10_for_topic = sorted_df.head(10)
    
    # Append the top 10 documents for the current topic to the result DataFrame
    top_10_documents_test1 = top_10_documents_test1.append(top_10_for_topic)

# Display the top 10 documents for all selected topics
top_10_documents_test1

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob
16081,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0
10046,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0
13619,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0
13552,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0
13542,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0
13476,US2012265556A1,Method and device for remote controlled applic...,55 . A device useful for monitoring of patient...,"['G16H40/67', 'A61B5/0022']","['G16H', 'A61B']",16,1.0
13366,US2012239705A1,Mobile information system for 12-lead ecg,1 . A 12-leads electrocardiograph mobile infor...,"['G06F17/30', 'G16H10/60']","['G06F', 'G16H']",16,1.0
23224,US2010217803A1,Interface device for communication between a m...,1 . A wireless interface device for communicat...,"['G16H40/67', 'G16H40/67']","['G16H', 'G16H']",16,1.0
23362,US2010253509A1,Personal environmental monitoring method and s...,"1 . A portable personal environmental monitor,...","['G08B1/08', 'G16H50/30']","['G08B', 'G16H']",16,1.0
23479,US2010283601A1,Medication usage monitoring and reminding devi...,"1 ) A device for monitoring medication usage, ...","['G16H10/60', 'A61J7/0418']","['G16H', 'A61J']",16,1.0
16154,US2008221928A1,System for Monitoring Patient Activity in a Me...,"1 . A method, for monitoring activity of a med...","['G06F19/00', 'G16H15/00']","['G06F', 'G16H']",25,1.0
9674,US2006287891A1,System and method in a computerized environmen...,1 . A method for displaying patient growth dat...,"['G06F19/00', 'G16H10/60']","['G06F', 'G16H']",25,1.0
16871,US2009089093A1,System and method to manage delivery of health...,1 . A method of managing delivery of healthcar...,"['G16H40/20', 'G16H20/00']","['G16H', 'G16H']",25,1.0
16825,US2009076418A1,Repetitive strain mitigation,1 . A method implemented in an environment tha...,"['A61B5/00', 'G16H40/63']","['A61B', 'G16H']",25,1.0
16804,US2009069742A1,Electronic Module for Mechanical Medication De...,1 . A method for wirelessly monitoring the ope...,"['G16H20/17', 'A61M5/31593']","['G16H', 'A61M']",25,1.0
16751,US2009052623A1,Virtual 4D treatment suite,1 . A method comprising: identifying relative ...,"['G16H70/20', 'A61N5/1031']","['G16H', 'A61N']",25,1.0
16508,US2008308452A1,Containers for transferring products and metho...,1 . A method for shipping a product comprising...,"['G16H40/20', 'G16H40/20']","['G16H', 'G16H']",25,1.0
16227,US2008235223A1,Online compliance document management system,1 . A method for a continuously monitoring a r...,"['G16H40/20', 'G06Q10/10']","['G16H', 'G06Q']",25,1.0
15484,US2008029439A1,Handheld waste scanning method,"1 . A method for sorting waste items, the meth...","['G16H40/20', 'A61B50/13']","['G16H', 'A61B']",25,1.0
15420,US2008009682A1,Method and system for clinical interpretation ...,1 . A method of clinically interpreting and re...,"['A61B5/00', 'G16H50/80']","['A61B', 'G16H']",25,1.0
23262,US2010228564A1,Method and apparatus for managing physician pr...,1 . An apparatus comprising: a computer appara...,"['G16H40/20', 'G16Z99/00']","['G16H', 'G16Z']",9,1.0
23314,US2010241445A1,Apparatus and method for effectuating a health...,1 . An apparatus comprising: a processor confi...,"['G06Q40/00', 'G16H20/10']","['G06Q', 'G16H']",9,1.0
22428,US2009313049A1,Apparatus and Method for Processing and/or Pro...,"1 . An apparatus, comprising: a processor, whe...","['G16H80/00', 'G06Q40/08']","['G16H', 'G06Q']",9,1.0
22482,US2010004948A1,"Apparatus, method, system and computer program...",1 . An apparatus comprising: a processor confi...,"['G16H20/30', 'G16H70/20']","['G16H', 'G16H']",9,1.0
22565,US2010023870A1,Apparatus and method for integrated management...,1 . An apparatus for use in an independent rev...,"['G16H10/20', 'G16H40/67']","['G16H', 'G16H']",9,1.0
22573,US2010030857A1,Method and apparatus for assisting behavioural...,1 . An apparatus for assisting behavioural cha...,"['G06F17/30', 'G16H20/70']","['G06F', 'G16H']",9,1.0
10033,US2007118635A1,"Medical diagnostic apparatus, medical network ...",1 . A medical diagnostic apparatus that is con...,"['G16H50/20', 'G16H30/20']","['G16H', 'G16H']",9,1.0
23159,US2010198571A1,Individualized Ranking of Risk of Health Outcomes,"1 . A data processing apparatus, comprising: o...","['G16H50/30', 'G16B5/00']","['G16H', 'G16B']",9,1.0
23249,US2010223070A1,Apparatus and method for mornitoring healthcar...,1 . An apparatus for controlling healthcare da...,"['G16H40/67', 'G16H40/67']","['G16H', 'G16H']",9,1.0
15887,US2008147440A1,Evidence-Based Medicine Supercharger,1 . An apparatus for processing medical litera...,"['G16Z99/00', 'G16H50/30']","['G16Z', 'G16H']",9,1.0
0,US2020097067A1,Artificial Intelligence System and Interactive...,"1 . A reality interactive responding system, c...","['G06F9/448', 'G16H40/67']","['G06F', 'G16H']",-1,0.0
20543,US2019160247A1,Process and system for generating personalized...,1 . A process for constructing a personalized ...,"['G06T19/20', 'G16H10/60']","['G06T', 'G16H']",-1,0.0
20525,US2019159733A1,Method and System for Monitoring Physiological...,1 . A system adapted for at least one health-r...,"['A61B5/0205', 'G16H40/63']","['A61B', 'G16H']",-1,0.0
20529,US2019159713A1,System and method for evaluating mental diseas...,What is claimed is: 1 . A system for evaluatin...,"['A61B5/024', 'G16H50/30']","['A61B', 'G16H']",-1,0.0
20530,US2019159744A1,Computed tomography perfusion (ctp) method and...,1 . A method of using computed tomography perf...,"['G06K9/20', 'G16H50/30']","['G06K', 'G16H']",-1,0.0
20531,US2019164651A1,Health task generation and population,We claim: 1 . A method of providing one or mor...,"['G16H50/30', 'G16H10/60']","['G16H', 'G16H']",-1,0.0
20532,US2019164019A1,Ultrasound Analytics for Actionable Information,What is claimed is: 1 . A monitoring system th...,"['B64C39/02', 'G16H50/70']","['B64C', 'G16H']",-1,0.0
20533,US2019161784A1,Precision therapeutic biomarker screening for ...,What is claimed: 1 . A method of identifying a...,"['G16H10/40', 'G16H10/40']","['G16H', 'G16H']",-1,0.0
20534,US2019164643A1,Method for controlling an evaluation device fo...,What is claimed is: 1 . A method for controlli...,"['G16H30/40', 'G06T7/33']","['G16H', 'G06T']",-1,0.0
20535,US2019159700A1,"Systems, apparatus, and methods for using a we...",What is claimed is: 1 . A computer-implemented...,"['G16H40/67', 'G06F2218/00']","['G16H', 'G06F']",-1,0.0
59,US2020105422A1,Patient care system for a home environment,"1 . A patient care system, comprising: a deplo...","['A61G7/10', 'G16H80/00']","['A61G', 'G16H']",39,1.0
16191,US2008228041A1,Method and System for Remote Diagnosis and Sup...,1 . A system for remote diagnosis comprising: ...,"['A61B5/00', 'G16H80/00']","['A61B', 'G16H']",39,1.0
17009,US2009125327A1,Systems And Methods For Voice Driven Health Da...,"1 . A health data tracker system, the system c...","['G16H40/63', 'G16H40/67']","['G16H', 'G16H']",39,1.0
16987,US2009112626A1,"Remote wireless monitoring, processing, and co...",1 . A system for remote wireless monitoring of...,"['G16H20/17', 'A61B5/7405']","['G16H', 'A61B']",39,1.0
16941,US2009103735A1,Telemedical system,1 . A telemedical system comprising: a first a...,"['G16H10/60', 'G16H40/67']","['G16H', 'G16H']",39,1.0
16881,US2009088605A1,System and method for interference mitigation ...,1 . A wireless patient monitoring system compr...,"['G16H40/67', 'A61B2560/0271']","['G16H', 'A61B']",39,1.0
16875,US2009088815A1,Proactive interactive limits override for impl...,1 . A system comprising an external device inc...,"['A61N1/08', 'G16H40/67']","['A61N', 'G16H']",39,1.0
16817,US2009076346A1,Tracking and Security for Adherent Patient Mon...,"1 . A patient monitoring system, comprising: a...","['G06F19/00', 'G16H10/60']","['G06F', 'G16H']",39,1.0
16813,US2009073991A1,Dynamic Pairing of Patients to Data Collection...,"1 . A system for monitoring a patient, the sys...","['H04L12/56', 'G16H40/67']","['H04L', 'G16H']",39,1.0
16633,US2009024002A1,Monitoring device for patient and monitoring s...,1 . A monitoring system comprising: a mobile c...,"['A61B5/00', 'G16H50/20']","['A61B', 'G16H']",39,1.0

In [23]:
num_records = top_10_documents_test1.shape[0]
num_records

50

# list of 100 queries

In [25]:
# Assuming you want to predict topics for the first 100 samples in 'df_claim_test'
num_samples_to_predict = 100

num_of_topics = 5
results = []

# Assuming you have a list of 100 queries in test
for query in df_claim_test['first_claim'][:num_samples_to_predict]:
    if isinstance(query, str):  # Check if the query is a string
        similar_topics, similarity = topic_model.find_topics(query, top_n=num_of_topics)
        results.append((similar_topics, similarity))
    else:
        # Handle cases where 'query' is not a string (e.g., it's a float)
        print(f"Skipping non-string query: {query}")

# Now, the 'results' list contains the similar topics and similarities for each query
# You can access the results for a specific query like this:
for i, (similar_topics, similarity) in enumerate(results):
    print(f"Query {i + 1}: Similar Topics {similar_topics}, Similarity {similarity}")

Skipping non-string query: nan
Skipping non-string query: nan
Query 1: Similar Topics [16, 25, 9, -1, 39], Similarity [0.7918744, 0.79018235, 0.7878056, 0.778339, 0.76860034]
Query 2: Similar Topics [16, 25, 22, 39, 40], Similarity [0.7235428, 0.71160823, 0.69949853, 0.68764395, 0.68443054]
Query 3: Similar Topics [6, 42, 19, 15, 21], Similarity [0.7082089, 0.69748014, 0.6785549, 0.6728228, 0.6512108]
Query 4: Similar Topics [19, 6, 34, 38, 17], Similarity [0.68264574, 0.66813165, 0.649974, 0.64888793, 0.6253784]
Query 5: Similar Topics [42, 24, 19, -1, 6], Similarity [0.68696046, 0.6848376, 0.6762146, 0.6728812, 0.6684448]
Query 6: Similar Topics [20, 25, 17, 12, 16], Similarity [0.7796078, 0.7527888, 0.7323582, 0.72718954, 0.72086835]
Query 7: Similar Topics [22, 40, 24, 16, 33], Similarity [0.83270305, 0.80476594, 0.7996713, 0.7931266, 0.79160213]
Query 8: Similar Topics [9, 28, 40, 24, 16], Similarity [0.7410316, 0.7391194, 0.7045108, 0.7033888, 0.69814295]
Query 9: Similar Topics [6, 42, 19, -1, 12], Similarity [0.790915, 0.78260344, 0.77113247, 0.69075054, 0.6839015]
Query 10: Similar Topics [15, 4, 14, 34, 13], Similarity [0.73293865, 0.70217717, 0.67159975, 0.66467804, 0.65992785]
Query 11: Similar Topics [7, 17, 12, 15, 25], Similarity [0.7602987, 0.7281624, 0.67599714, 0.6570859, 0.6495148]
Query 12: Similar Topics [6, 42, 19, 24, 38], Similarity [0.85710305, 0.80751497, 0.78049356, 0.7272686, 0.72356284]
Query 13: Similar Topics [16, 39, 20, -1, 24], Similarity [0.77035064, 0.76472485, 0.7624798, 0.75272083, 0.74724925]
Query 14: Similar Topics [24, 28, 33, 5, 25], Similarity [0.71608084, 0.6954855, 0.6854737, 0.6844556, 0.6823045]
Query 15: Similar Topics [25, 4, 12, 17, 20], Similarity [0.7930302, 0.7533845, 0.75023246, 0.7475581, 0.742283]
Query 16: Similar Topics [22, 19, 20, 42, 6], Similarity [0.77602464, 0.7725879, 0.76013327, 0.7409954, 0.73528075]
Query 17: Similar Topics [20, 8, 38, 44, 0], Similarity [0.68633795, 0.6817894, 0.617368, 0.60856956, 0.59066594]
Query 18: Similar Topics [20, 42, 8, 6, 19], Similarity [0.7998545, 0.7944697, 0.79093957, 0.78226537, 0.76147604]
Query 19: Similar Topics [20, 16, 8, 25, 39], Similarity [0.8218689, 0.7603169, 0.75408655, 0.7323127, 0.7144551]
Query 20: Similar Topics [24, 32, 5, 12, 39], Similarity [0.8853781, 0.8780143, 0.845062, 0.84323263, 0.8349736]
Query 21: Similar Topics [7, 17, 15, 12, 4], Similarity [0.78169996, 0.7470095, 0.7028605, 0.68070275, 0.6772118]
Query 22: Similar Topics [21, 15, 4, 12, 14], Similarity [0.7347168, 0.7101221, 0.67619455, 0.6636331, 0.66118175]
Query 23: Similar Topics [12, 28, 41, 25, 1], Similarity [0.7850708, 0.74583054, 0.74546057, 0.73668605, 0.7328857]
Query 24: Similar Topics [25, 28, -1, 37, 20], Similarity [0.768734, 0.76306295, 0.7550368, 0.75381565, 0.74055433]
Query 25: Similar Topics [22, 12, 24, 33, 40], Similarity [0.7411468, 0.7382261, 0.7237878, 0.70347774, 0.7022985]
Query 26: Similar Topics [21, 15, 4, 12, 33], Similarity [0.8341559, 0.8205466, 0.80869806, 0.8014784, 0.79533964]
Query 27: Similar Topics [38, 32, 42, 24, 34], Similarity [0.69969606, 0.62568533, 0.6187009, 0.61725605, 0.61049473]
Query 28: Similar Topics [12, 24, -1, 16, 25], Similarity [0.7806669, 0.77471566, 0.7618256, 0.7609506, 0.7490692]
Query 29: Similar Topics [7, 17, 37, 15, -1], Similarity [0.6962472, 0.6581679, 0.58785415, 0.5868042, 0.57696396]
Query 30: Similar Topics [39, 24, 5, 32, 16], Similarity [0.8266052, 0.82273245, 0.79309094, 0.7852653, 0.76493263]
Query 31: Similar Topics [6, 42, 19, 44, 24], Similarity [0.8390347, 0.79483306, 0.7669208, 0.7097598, 0.7060151]
Query 32: Similar Topics [38, 20, 16, 9, 24], Similarity [0.70972645, 0.62808985, 0.61994344, 0.61911, 0.6143558]
Query 33: Similar Topics [15, 4, 21, 25, 12], Similarity [0.73220474, 0.6964865, 0.6958034, 0.6876447, 0.6860511]
Query 34: Similar Topics [42, 6, 38, 19, 39], Similarity [0.7633394, 0.73871124, 0.724936, 0.7167308, 0.7113094]
Query 35: Similar Topics [24, 40, 13, 5, 39], Similarity [0.7356844, 0.7178196, 0.7068573, 0.706078, 0.7002866]
Query 36: Similar Topics [24, 13, 14, 32, 39], Similarity [0.8201561, 0.8133374, 0.80902463, 0.7928106, 0.79131013]
Query 37: Similar Topics [25, 12, 17, 11, 20], Similarity [0.7881396, 0.78411555, 0.7717463, 0.7597242, 0.7575947]
Query 38: Similar Topics [20, 16, 24, 32, 38], Similarity [0.76075065, 0.75956166, 0.7501062, 0.743603, 0.73537827]
Query 39: Similar Topics [24, 39, 5, 13, 40], Similarity [0.7334182, 0.7208829, 0.6948497, 0.6898939, 0.6851994]
Query 40: Similar Topics [24, 38, 42, 39, -1], Similarity [0.76916957, 0.74912477, 0.7485341, 0.7479552, 0.7474344]
Query 41: Similar Topics [22, 24, 16, 49, 12], Similarity [0.87076235, 0.77660424, 0.7719773, 0.76717216, 0.7597858]
Query 42: Similar Topics [22, 12, 4, 21, 15], Similarity [0.8353751, 0.7803861, 0.7755386, 0.7719233, 0.7694642]
Query 43: Similar Topics [6, 42, 19, -1, 16], Similarity [0.7701096, 0.7691077, 0.7378681, 0.6651392, 0.65762615]
Query 44: Similar Topics [15, 12, 25, -1, 17], Similarity [0.76824, 0.7531524, 0.747255, 0.7470882, 0.74229205]
Query 45: Similar Topics [32, 42, 20, 8, 24], Similarity [0.7847367, 0.7808808, 0.7740774, 0.7674838, 0.7607498]
Query 46: Similar Topics [19, 6, 42, 25, 12], Similarity [0.7970326, 0.76375496, 0.7565299, 0.72618455, 0.72015154]
Query 47: Similar Topics [20, 8, 39, 24, 40], Similarity [0.7888652, 0.6855217, 0.6798723, 0.6767732, 0.65674543]
Query 48: Similar Topics [21, 15, 4, 14, 12], Similarity [0.74253464, 0.7157552, 0.714765, 0.6938007, 0.67414325]
Query 49: Similar Topics [21, 15, 4, 12, 11], Similarity [0.7571208, 0.6992961, 0.6601994, 0.6591481, 0.65543294]
Query 50: Similar Topics [6, 19, 42, 22, -1], Similarity [0.7852407, 0.76281345, 0.7218099, 0.6774099, 0.6660595]
Query 51: Similar Topics [6, 42, 19, -1, 10], Similarity [0.81202096, 0.75521475, 0.741732, 0.6740673, 0.6684128]
Query 52: Similar Topics [12, 15, 17, 4, 7], Similarity [0.72829866, 0.72304815, 0.717803, 0.714995, 0.7071822]
Query 53: Similar Topics [13, 32, -1, 24, 27], Similarity [0.75384915, 0.7309787, 0.7231175, 0.72247326, 0.71820533]
Query 54: Similar Topics [17, 34, 25, 15, -1], Similarity [0.72452396, 0.7221061, 0.7113738, 0.70802134, 0.690488]
Query 55: Similar Topics [6, 42, 19, 38, 39], Similarity [0.7200218, 0.6989205, 0.66061306, 0.65413654, 0.65065944]
Query 56: Similar Topics [33, 12, 25, 4, 17], Similarity [0.7809683, 0.76544124, 0.7560595, 0.7382468, 0.7351943]
Query 57: Similar Topics [22, 21, 19, 12, 49], Similarity [0.8481984, 0.76740444, 0.76301694, 0.76079345, 0.75849736]
Query 58: Similar Topics [39, 24, 5, 32, 16], Similarity [0.8611214, 0.8404311, 0.8034959, 0.7981434, 0.7883991]
Query 59: Similar Topics [25, 20, 17, -1, 12], Similarity [0.7664138, 0.7548897, 0.7545855, 0.73758245, 0.73055327]
Query 60: Similar Topics [15, 33, 12, 4, 28], Similarity [0.79503, 0.764988, 0.7645227, 0.7555517, 0.75306475]
Query 61: Similar Topics [28, 25, 33, 12, 4], Similarity [0.80906814, 0.7789366, 0.7623515, 0.75789416, 0.72365075]
Query 62: Similar Topics [24, 13, 5, 32, -1], Similarity [0.7812767, 0.76641273, 0.7579602, 0.7456571, 0.7354984]
Query 63: Similar Topics [24, 5, 39, 13, -1], Similarity [0.74831736, 0.72634417, 0.7229068, 0.71878475, 0.71822006]
Query 64: Similar Topics [6, 19, 42, 9, 38], Similarity [0.8478438, 0.78894824, 0.7885786, 0.78013855, 0.7263964]
Query 65: Similar Topics [16, 40, 22, 24, 9], Similarity [0.7458052, 0.7413729, 0.7196479, 0.71381366, 0.7082827]
Query 66: Similar Topics [19, 42, 6, 13, 38], Similarity [0.7284474, 0.6827109, 0.67599195, 0.65263826, 0.6248299]
Query 67: Similar Topics [22, 28, 40, 16, 24], Similarity [0.78473455, 0.7797787, 0.77157056, 0.76881576, 0.75900614]
Query 68: Similar Topics [39, 24, 20, 13, 16], Similarity [0.7328385, 0.7290685, 0.727893, 0.7058241, 0.7044662]
Query 69: Similar Topics [19, 42, 6, -1, 9], Similarity [0.7840872, 0.78231716, 0.77389276, 0.7334223, 0.72283363]
Query 70: Similar Topics [38, 32, 24, 20, 39], Similarity [0.6507989, 0.62711585, 0.6199895, 0.6158411, 0.614372]
Query 71: Similar Topics [-1, 28, 20, 24, 9], Similarity [0.70274645, 0.6958298, 0.6938486, 0.69262755, 0.69213927]
Query 72: Similar Topics [22, 20, 12, 24, 25], Similarity [0.78979397, 0.7840443, 0.7342716, 0.7311079, 0.72505933]
Query 73: Similar Topics [6, 19, 42, 20, 8], Similarity [0.8136555, 0.75536215, 0.746436, 0.743284, 0.6997022]
Query 74: Similar Topics [6, 9, 42, 19, 14], Similarity [0.81428885, 0.7668264, 0.76657605, 0.754428, 0.7393341]
Query 75: Similar Topics [46, 38, -1, 26, 7], Similarity [0.6735556, 0.672274, 0.65666807, 0.6534355, 0.6528863]
Query 76: Similar Topics [38, 20, 9, 34, 14], Similarity [0.6938319, 0.63669175, 0.633377, 0.6241983, 0.6103877]
Query 77: Similar Topics [20, 8, 39, 16, 24], Similarity [0.8390935, 0.7860417, 0.7568383, 0.74735725, 0.73831207]
Query 78: Similar Topics [19, 42, 6, 16, 38], Similarity [0.74477375, 0.73538774, 0.72445214, 0.6633568, 0.65390706]
Query 79: Similar Topics [6, 42, 19, 38, 24], Similarity [0.8099507, 0.77188194, 0.72580814, 0.6846053, 0.6823086]
Query 80: Similar Topics [42, 19, 6, -1, 28], Similarity [0.733833, 0.7173463, 0.7081105, 0.6769976, 0.6661862]
Query 81: Similar Topics [15, 4, 12, 25, 21], Similarity [0.7207088, 0.6983321, 0.6891618, 0.6670431, 0.665388]
Query 82: Similar Topics [24, 5, 32, 39, 16], Similarity [0.8196472, 0.8058765, 0.8041114, 0.802922, 0.7862577]
Query 83: Similar Topics [6, 42, 19, 38, 16], Similarity [0.8705776, 0.8160876, 0.80497074, 0.7677382, 0.761811]
Query 84: Similar Topics [6, 42, 19, 28, 16], Similarity [0.81762683, 0.7552103, 0.740836, 0.6965718, 0.67208576]
Query 85: Similar Topics [6, 42, 7, 19, 17], Similarity [0.6382115, 0.6254957, 0.62264943, 0.6180501, 0.6063882]
Query 86: Similar Topics [12, 1, 11, 24, 22], Similarity [0.8548677, 0.8277128, 0.82284814, 0.8226967, 0.81891286]
Query 87: Similar Topics [50, 38, 44, 23, -1], Similarity [0.7417844, 0.7333375, 0.73074436, 0.7237232, 0.72001874]
Query 88: Similar Topics [16, 12, 25, 1, 24], Similarity [0.7799389, 0.77812666, 0.76425576, 0.76317483, 0.751726]
Query 89: Similar Topics [42, 6, 19, 38, 24], Similarity [0.8360308, 0.80921376, 0.77766895, 0.738999, 0.7338301]
Query 90: Similar Topics [6, 14, 42, 19, 13], Similarity [0.8155235, 0.77472997, 0.76076597, 0.76020443, 0.7508242]
Query 91: Similar Topics [12, 25, 33, 28, 17], Similarity [0.7611239, 0.7502265, 0.73292863, 0.7244704, 0.72088563]
Query 92: Similar Topics [19, 42, 6, -1, 25], Similarity [0.7792612, 0.77392757, 0.7738666, 0.76233214, 0.75166774]
Query 93: Similar Topics [6, 42, 19, 34, 37], Similarity [0.7752775, 0.75394607, 0.7379747, 0.7276006, 0.7107315]
Query 94: Similar Topics [24, 13, 22, 32, 16], Similarity [0.79399633, 0.7658917, 0.75795734, 0.7544646, 0.74355614]
Query 95: Similar Topics [33, 12, 25, 40, -1], Similarity [0.69365644, 0.6878832, 0.6874579, 0.6807748, 0.6785824]
Query 96: Similar Topics [38, 19, 6, 42, 24], Similarity [0.76865995, 0.6972545, 0.68962705, 0.684732, 0.6720605]
Query 97: Similar Topics [42, 32, 19, -1, 6], Similarity [0.7872604, 0.7807087, 0.78043, 0.77734256, 0.7698184]
Query 98: Similar Topics [42, 6, 19, 24, 32], Similarity [0.87026894, 0.8373989, 0.80398834, 0.78871846, 0.7779737]

In [28]:
# Assuming you want to predict topics for the first 100 samples in 'df_Abstract_test'
num_samples_to_predict = 100

num_of_topics = 5
results = []

# Create an empty DataFrame to store the results
result_df_q = pd.DataFrame(columns=['query_publication_numbers', 'query_class_codes', 'query_claim', 'query_predicted_topics'])

# Assuming you have a list of 100 queries in 'df_Abstract_test'
for i, (query, publication_number, first_claim, class_codes) in enumerate(zip(df_claim_test['first_claim'][:num_samples_to_predict], 
                                                    df_claim_test['publication_numbers'][:num_samples_to_predict],
                                                    df_claim_test['first_claim'][:num_samples_to_predict],
                                                    df_claim_test['class_codes'][:num_samples_to_predict])):
    # Check if the 'first_claim' is a string before processing
    if isinstance(query, str):
        similar_topics, similarity = topic_model.find_topics(query, top_n=num_of_topics)
        results.append((similar_topics, similarity))
        
        # Store the results in the DataFrame
        result_df_q = result_df_q.append({
            'query_claim': query,
            'query_predicted_topics': similar_topics,
            'query_publication_numbers': publication_number,
            'query_class_codes': class_codes
        }, ignore_index=True)
    else:
        # Handle cases where 'query' is not a string (e.g., it's a nan value)
        print(f"Skipping non-string query: {query}")

result_df_q

Skipping non-string query: nan
Skipping non-string query: nan

,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics
0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,"[16, 25, 9, -1, 39]"
1,US20230270344A1,"A61B5/02405,A61B5/01,A61B5/16,A61B5/02055,A61B...","1. A monitoring device, comprising:\na band co...","[16, 25, 22, 39, 40]"
2,US20230200909A1,"A61B17/17,A61B2090/061,A61B90/06,A61B2090/365,...",1-25. (canceled) 26. A method for guiding a fr...,"[6, 42, 19, 15, 21]"
3,US20230218347A1,"G06V10/46,G06V20/698,G06T2207/20112,G06T7/13,A...",1-184. (canceled) 185. A computer-implemented ...,"[19, 6, 34, 38, 17]"
4,US20230063013A1,"H04M1/72418,G08B,G08,G08B25/016,G,H04W4/023,G1...",1. (canceled) 2. A community based response sy...,"[42, 24, 19, -1, 6]"
...,...,...,...,...
93,US20230017310A1,"G06Q10/10,G,G06F,G06F16/90,G06F16/95,G16H30/20...",1. A system for storing medical information re...,"[24, 13, 22, 32, 16]"
94,US20230091925A1,"H04L41/5061,G,G06,G06F,H04L67/00,H,H04,G06F16/...",1. A method for event notification in an inter...,"[33, 12, 25, 40, -1]"
95,US20230010638A1,"A61M5/142,A61,Y10S128/00,G06T2219/2016,G06F8/6...",1.-2. (canceled) 3. A method of managing an in...,"[38, 19, 6, 42, 24]"
96,US20230009812A1,"A61B5/14551,A61,G,A61B5/021,A61B5/746,A61B,A61...",1. (canceled) 2. A patient monitoring system c...,"[42, 32, 19, -1, 6]"
97,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,"[42, 6, 19, 24, 32]"

In [29]:
import pandas as pd

# Create an empty DataFrame to store the results
result_df = pd.DataFrame(columns=['publication_number', 'title', 'first_claim', 'sub_classes', 'sub_class', 'topics', 'prob', 'query_publication_numbers', 'query_class_codes', 'query_claim', 'query_predicted_topics'])

# Define the number of documents to retrieve for each topic
num_of_documents_to_retrieve = 10

for i, row in result_df_q.iterrows():
    query = row['query_claim']
    predicted_topics = row['query_predicted_topics']
    
    for topic_id in predicted_topics:
        # Filter 'df_Abstract_topic' to get the top 'num_of_documents_to_retrieve' documents for the current topic_id
        topic_documents = df_claim_topic[df_claim_topic['topics'] == topic_id]
        
        # Sort the documents by probability in descending order
        topic_documents = topic_documents.sort_values(by='prob', ascending=False).head(num_of_documents_to_retrieve)
        
        # Append the results to the 'result_df' DataFrame
        for _, doc_row in topic_documents.iterrows():
            result_df = result_df.append({
                'query_publication_numbers': row['query_publication_numbers'],
                'query_class_codes': row['query_class_codes'],
                'query_claim': query,
                'query_predicted_topics': [topic_id],  # Assign the current topic_id as a list
                'publication_number': doc_row['publication_number'],
                'title': doc_row['title'],
                'first_claim': doc_row['first_claim'],
                'sub_classes': doc_row['sub_classes'],
                'sub_class': doc_row['sub_class'],
                'topics': doc_row['topics'],
                'prob': doc_row['prob']
            }, ignore_index=True)

# Now, 'result_df' contains the top 10 most probable documents for each predicted topic list for each query
result_df

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics
0,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16]
1,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16]
2,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16]
3,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16]
4,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16]
...,...,...,...,...,...,...,...,...,...,...,...
4895,US2018068076A1,Systems and methods for semantic search and ex...,1 . A system that facilitates using user-enter...,"['G16H50/20', 'G06F16/90344']","['G16H', 'G06F']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32]
4896,US2007055543A1,Medical resource estimation and simulation system,1 . A healthcare decision support system for s...,"['G16H10/60', 'G16Z99/00']","['G16H', 'G16Z']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32]
4897,US2007055545A1,System and user interface for processing patie...,1 . A system for use in processing patient cli...,"['G06F19/00', 'G16H50/20']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32]
4898,US2006271556A1,System and method for integration of medical i...,1 . A system for integrating medical informati...,"['G06F17/30', 'G16H70/00']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32]
4899,US2006241978A1,Electronic clinical chart system,1 . An electronic clinical chart system compri...,"['G16H50/70', 'G16B25/00']","['G16H', 'G16B']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32]

In [30]:
result_df['query_class_codes'][0]

'A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/7221,A61B5/14532,G16H40/00,A61B5/14546,G16H40/60,A61B5/68,A61B2562/08,H,A61B1/00,A61B2562/221,A61B5/7475,A61B2562/18,A61B5/746,A61B5/7405,H05K,G16H40/67,A61B,Y10,A61B5/6813,Y,A61B2562/185,G16H10/40,A61B5/6826,A61B5/02,A61B5/0002,A61B5/1455,A61B5/6832,A,A61B5/7235,A61B5/6801,A61B5/7278,G16H,A61B5/026,A61B5/742,A61B2562/22,A61B5/024,G16,A61B5/02416,A61B5/683,A61B5/0015,A61B5/6825,Y10S,A61B5/1495,A61B5/72,A61B5/0261,A61B2562/085,A61B2562/222,A61B5/7275,A61B5/00,A61B5/145,A61B5/74,G16H10/00,H05K999/99,A61B5/7246,Y10S439/909,A61B5/14552,A61B5/6838,A61B5/6815,A61B5/7271,H05K999/00,A61B5/02427,A61B5/0205,Y10S439/00,A61B5/0022,A61B5/6814,A61B2562/00,H05'

In [31]:
# Add a new column to store the filtered codes
result_df['query_codes_G16H'] = ''

# Define a function to extract codes starting with 'G61H' from the class codes
def extract_G16H_codes(class_codes):
    codes = class_codes.split(',')
    return ','.join([code for code in codes if code.startswith('G16H')])

# Iterate through rows and update the 'query_codes_G61H' column
for index, row in result_df.iterrows():
    class_codes = row['query_class_codes']
    filtered_codes = extract_G16H_codes(class_codes)
    result_df.at[index, 'query_codes_G16H'] = filtered_codes

# Display the updated DataFrame
result_df

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics,query_codes_G16H
0,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G..."
1,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G..."
2,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G..."
3,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G..."
4,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4895,US2018068076A1,Systems and methods for semantic search and ex...,1 . A system that facilitates using user-enter...,"['G16H50/20', 'G06F16/90344']","['G16H', 'G06F']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60"
4896,US2007055543A1,Medical resource estimation and simulation system,1 . A healthcare decision support system for s...,"['G16H10/60', 'G16Z99/00']","['G16H', 'G16Z']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60"
4897,US2007055545A1,System and user interface for processing patie...,1 . A system for use in processing patient cli...,"['G06F19/00', 'G16H50/20']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60"
4898,US2006271556A1,System and method for integration of medical i...,1 . A system for integrating medical informati...,"['G06F17/30', 'G16H70/00']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60"
4899,US2006241978A1,Electronic clinical chart system,1 . An electronic clinical chart system compri...,"['G16H50/70', 'G16B25/00']","['G16H', 'G16B']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60"

In [32]:
import ast


# Create a new column to store the common code
result_df['exact_match_code'] = ''

# Iterate through rows and compare 'sub_classes' and 'query_codes_G16H'
for index, row in result_df.iterrows():
    sub_classes_str = row['sub_classes']  # Data format in this field "['A61B5/00', 'G16H40/67']"
    query_codes_G16H = row['query_codes_G16H']  # Data format in this field 'G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H'
    
    # Convert the sub_classes string to a list
    sub_classes = ast.literal_eval(sub_classes_str)
    
    # Split the codes into lists
    sub_class_list = [code.strip() for code in sub_classes]
    query_codes_list = query_codes_G16H.split(',')
    
    # Check for common codes
    exact_match_code = [code for code in sub_class_list if code in query_codes_list]
    
    # Join the common codes into a single string
    exact_match_code_str = ','.join(exact_match_code)
    
    # Update the 'exact_match_code' column with the exact_match_code
    result_df.at[index, 'exact_match_code'] = exact_match_code_str
    
    # Debugging statements
    #print(f'Row {index}: sub_classes={sub_classes}, query_codes_G16H={query_codes_G16H}, common_codes={common_codes_str}')

# Display the updated DataFrame
result_df

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics,query_codes_G16H,exact_match_code
0,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",
1,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",
2,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",
3,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",
4,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,US2018068076A1,Systems and methods for semantic search and ex...,1 . A system that facilitates using user-enter...,"['G16H50/20', 'G06F16/90344']","['G16H', 'G06F']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",
4896,US2007055543A1,Medical resource estimation and simulation system,1 . A healthcare decision support system for s...,"['G16H10/60', 'G16Z99/00']","['G16H', 'G16Z']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",G16H10/60
4897,US2007055545A1,System and user interface for processing patie...,1 . A system for use in processing patient cli...,"['G06F19/00', 'G16H50/20']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",
4898,US2006271556A1,System and method for integration of medical i...,1 . A system for integrating medical informati...,"['G06F17/30', 'G16H70/00']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",
4899,US2006241978A1,Electronic clinical chart system,1 . An electronic clinical chart system compri...,"['G16H50/70', 'G16B25/00']","['G16H', 'G16B']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",

In [33]:
# result_df.sample(n=100)

In [34]:
# Calculate the count of 'exact_match_code' for each group and assign it to all rows within the group
result_df['count_exact_match'] = result_df.groupby('query_publication_numbers')['exact_match_code'].transform(lambda x: x[x != ''].count())
result_df

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics,query_codes_G16H,exact_match_code,count_exact_match
0,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
1,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
2,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
3,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
4,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,US2018068076A1,Systems and methods for semantic search and ex...,1 . A system that facilitates using user-enter...,"['G16H50/20', 'G06F16/90344']","['G16H', 'G06F']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",,16
4896,US2007055543A1,Medical resource estimation and simulation system,1 . A healthcare decision support system for s...,"['G16H10/60', 'G16Z99/00']","['G16H', 'G16Z']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",G16H10/60,16
4897,US2007055545A1,System and user interface for processing patie...,1 . A system for use in processing patient cli...,"['G06F19/00', 'G16H50/20']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",,16
4898,US2006271556A1,System and method for integration of medical i...,1 . A system for integrating medical informati...,"['G06F17/30', 'G16H70/00']","['G06F', 'G16H']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",,16
4899,US2006241978A1,Electronic clinical chart system,1 . An electronic clinical chart system compri...,"['G16H50/70', 'G16B25/00']","['G16H', 'G16B']",32,1.0,US20230138516A1,"G16H,G16H10/00,G06Q10/1093,G06Q10/10,G16,G06Q1...",1-27. (canceled) 28. A system to manage record...,[32],"G16H,G16H10/00,G16H40/20,G16H40/00,G16H10/60",,16

In [36]:
filtered_df = result_df[result_df['query_publication_numbers'] == 'US20230238130A1']
filtered_df

,publication_number,title,first_claim,sub_classes,sub_class,topics,prob,query_publication_numbers,query_class_codes,query_claim,query_predicted_topics,query_codes_G16H,exact_match_code,count_exact_match
0,US2008198033A1,Device for Communicating with a Voice-Disabled...,1 . A hand-held communication device comprisin...,"['G09B21/00', 'G16H40/63']","['G09B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
1,US2007118397A1,Monitoring of medical conditions,1 . A device for use in the provision of a med...,"['G16H10/20', 'A61B5/24']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
2,US2012303331A1,Adapter between scale and vital signs monitor,"1 . A method comprising: receiving, at an adap...","['G06F15/00', 'G16H40/63']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
3,US2012286959A1,Automated Allergy Alerts,1 . A wireless communication device comprising...,"['G16H10/60', 'G08B21/043']","['G16H', 'G08B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
4,US2012280049A1,Personal Health Record (PHR) ID card claiming ...,"1 . A customizable, portable identification an...","['G06K19/06', 'G16H10/65']","['G06K', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
5,US2012265556A1,Method and device for remote controlled applic...,55 . A device useful for monitoring of patient...,"['G16H40/67', 'A61B5/0022']","['G16H', 'A61B']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
6,US2012239705A1,Mobile information system for 12-lead ecg,1 . A 12-leads electrocardiograph mobile infor...,"['G06F17/30', 'G16H10/60']","['G06F', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
7,US2010217803A1,Interface device for communication between a m...,1 . A wireless interface device for communicat...,"['G16H40/67', 'G16H40/67']","['G16H', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...","G16H40/67,G16H40/67",12
8,US2010253509A1,Personal environmental monitoring method and s...,"1 . A portable personal environmental monitor,...","['G08B1/08', 'G16H50/30']","['G08B', 'G16H']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
9,US2010283601A1,Medication usage monitoring and reminding devi...,"1 ) A device for monitoring medication usage, ...","['G16H10/60', 'A61J7/0418']","['G16H', 'A61J']",16,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[16],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
10,US2008221928A1,System for Monitoring Patient Activity in a Me...,"1 . A method, for monitoring activity of a med...","['G06F19/00', 'G16H15/00']","['G06F', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
11,US2006287891A1,System and method in a computerized environmen...,1 . A method for displaying patient growth dat...,"['G06F19/00', 'G16H10/60']","['G06F', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
12,US2009089093A1,System and method to manage delivery of health...,1 . A method of managing delivery of healthcar...,"['G16H40/20', 'G16H20/00']","['G16H', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
13,US2009076418A1,Repetitive strain mitigation,1 . A method implemented in an environment tha...,"['A61B5/00', 'G16H40/63']","['A61B', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
14,US2009069742A1,Electronic Module for Mechanical Medication De...,1 . A method for wirelessly monitoring the ope...,"['G16H20/17', 'A61M5/31593']","['G16H', 'A61M']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
15,US2009052623A1,Virtual 4D treatment suite,1 . A method comprising: identifying relative ...,"['G16H70/20', 'A61N5/1031']","['G16H', 'A61N']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
16,US2008308452A1,Containers for transferring products and metho...,1 . A method for shipping a product comprising...,"['G16H40/20', 'G16H40/20']","['G16H', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
17,US2008235223A1,Online compliance document management system,1 . A method for a continuously monitoring a r...,"['G16H40/20', 'G06Q10/10']","['G16H', 'G06Q']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
18,US2008029439A1,Handheld waste scanning method,"1 . A method for sorting waste items, the meth...","['G16H40/20', 'A61B50/13']","['G16H', 'A61B']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
19,US2008009682A1,Method and system for clinical interpretation ...,1 . A method of clinically interpreting and re...,"['A61B5/00', 'G16H50/80']","['A61B', 'G16H']",25,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[25],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
20,US2010228564A1,Method and apparatus for managing physician pr...,1 . An apparatus comprising: a computer appara...,"['G16H40/20', 'G16Z99/00']","['G16H', 'G16Z']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
21,US2010241445A1,Apparatus and method for effectuating a health...,1 . An apparatus comprising: a processor confi...,"['G06Q40/00', 'G16H20/10']","['G06Q', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
22,US2009313049A1,Apparatus and Method for Processing and/or Pro...,"1 . An apparatus, comprising: a processor, whe...","['G16H80/00', 'G06Q40/08']","['G16H', 'G06Q']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
23,US2010004948A1,"Apparatus, method, system and computer program...",1 . An apparatus comprising: a processor confi...,"['G16H20/30', 'G16H70/20']","['G16H', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
24,US2010023870A1,Apparatus and method for integrated management...,1 . An apparatus for use in an independent rev...,"['G16H10/20', 'G16H40/67']","['G16H', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
25,US2010030857A1,Method and apparatus for assisting behavioural...,1 . An apparatus for assisting behavioural cha...,"['G06F17/30', 'G16H20/70']","['G06F', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
26,US2007118635A1,"Medical diagnostic apparatus, medical network ...",1 . A medical diagnostic apparatus that is con...,"['G16H50/20', 'G16H30/20']","['G16H', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
27,US2010198571A1,Individualized Ranking of Risk of Health Outcomes,"1 . A data processing apparatus, comprising: o...","['G16H50/30', 'G16B5/00']","['G16H', 'G16B']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
28,US2010223070A1,Apparatus and method for mornitoring healthcar...,1 . An apparatus for controlling healthcare da...,"['G16H40/67', 'G16H40/67']","['G16H', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...","G16H40/67,G16H40/67",12
29,US2008147440A1,Evidence-Based Medicine Supercharger,1 . An apparatus for processing medical litera...,"['G16Z99/00', 'G16H50/30']","['G16Z', 'G16H']",9,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[9],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
30,US2020097067A1,Artificial Intelligence System and Interactive...,"1 . A reality interactive responding system, c...","['G06F9/448', 'G16H40/67']","['G06F', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
31,US2019160247A1,Process and system for generating personalized...,1 . A process for constructing a personalized ...,"['G06T19/20', 'G16H10/60']","['G06T', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
32,US2019159733A1,Method and System for Monitoring Physiological...,1 . A system adapted for at least one health-r...,"['A61B5/0205', 'G16H40/63']","['A61B', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
33,US2019159713A1,System and method for evaluating mental diseas...,What is claimed is: 1 . A system for evaluatin...,"['A61B5/024', 'G16H50/30']","['A61B', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
34,US2019159744A1,Computed tomography perfusion (ctp) method and...,1 . A method of using computed tomography perf...,"['G06K9/20', 'G16H50/30']","['G06K', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
35,US2019164651A1,Health task generation and population,We claim: 1 . A method of providing one or mor...,"['G16H50/30', 'G16H10/60']","['G16H', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
36,US2019164019A1,Ultrasound Analytics for Actionable Information,What is claimed is: 1 . A monitoring system th...,"['B64C39/02', 'G16H50/70']","['B64C', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
37,US2019161784A1,Precision therapeutic biomarker screening for ...,What is claimed: 1 . A method of identifying a...,"['G16H10/40', 'G16H10/40']","['G16H', 'G16H']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...","G16H10/40,G16H10/40",12
38,US2019164643A1,Method for controlling an evaluation device fo...,What is claimed is: 1 . A method for controlli...,"['G16H30/40', 'G06T7/33']","['G16H', 'G06T']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
39,US2019159700A1,"Systems, apparatus, and methods for using a we...",What is claimed is: 1 . A computer-implemented...,"['G16H40/67', 'G06F2218/00']","['G16H', 'G06F']",-1,0.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[-1],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
40,US2020105422A1,Patient care system for a home environment,"1 . A patient care system, comprising: a deplo...","['A61G7/10', 'G16H80/00']","['A61G', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
41,US2008228041A1,Method and System for Remote Diagnosis and Sup...,1 . A system for remote diagnosis comprising: ...,"['A61B5/00', 'G16H80/00']","['A61B', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
42,US2009125327A1,Systems And Methods For Voice Driven Health Da...,"1 . A health data tracker system, the system c...","['G16H40/63', 'G16H40/67']","['G16H', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
43,US2009112626A1,"Remote wireless monitoring, processing, and co...",1 . A system for remote wireless monitoring of...,"['G16H20/17', 'A61B5/7405']","['G16H', 'A61B']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
44,US2009103735A1,Telemedical system,1 . A telemedical system comprising: a first a...,"['G16H10/60', 'G16H40/67']","['G16H', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
45,US2009088605A1,System and method for interference mitigation ...,1 . A wireless patient monitoring system compr...,"['G16H40/67', 'A61B2560/0271']","['G16H', 'A61B']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
46,US2009088815A1,Proactive interactive limits override for impl...,1 . A system comprising an external device inc...,"['A61N1/08', 'G16H40/67']","['A61N', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
47,US2009076346A1,Tracking and Security for Adherent Patient Mon...,"1 . A patient monitoring system, comprising: a...","['G06F19/00', 'G16H10/60']","['G06F', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12
48,US2009073991A1,Dynamic Pairing of Patients to Data Collection...,"1 . A system for monitoring a patient, the sys...","['H04L12/56', 'G16H40/67']","['H04L', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",G16H40/67,12
49,US2009024002A1,Monitoring device for patient and monitoring s...,1 . A monitoring system comprising: a mobile c...,"['A61B5/00', 'G16H50/20']","['A61B', 'G16H']",39,1.0,US20230238130A1,"A61B5/14551,A61,A61B5/0295,A61B5/6829,G,A61B5/...",1. A physiological monitoring device comprisin...,[39],"G16H40/00,G16H40/60,G16H40/67,G16H10/40,G16H,G...",,12